Use Stop Code as Stop ID where Applicable
opentripplanner/otp-ui pull request #360
Opened 2022-03-08 18:07 UTC by miles-grant-ibigroup

This PR uses stop ID instead of stop code when it makes sense to. This makes the stop ID more useful for users.

2022-03-11 19:36 UTC, daniel-heppner-ibigroup approved these changes
LGTM

2022-03-14 19:02 UTC, binh-dam-ibigroup requested changes
The fallback to stop id doesn't seem to work in the default stops-overlay rendering.

2022-03-14 21:41 UTC, miles-grant-ibigroup commented on packages/stops-overlay/src/default-stop-marker.js
> +    const userFacingId = code || id.split(":")[1];
This bug is also present in master, seems to be a case of the mock data not reflecting actual OTP responses. Either way, have fixed it here in 3e6aebba63fc90f9bbe3912bb8118507c2e14a6b

2022-03-14 21:55 UTC, miles-grant-ibigroup commented
Thanks for the thorough review! All addressed

2022-03-15 13:25 UTC, binh-dam-ibigroup commented on packages/stops-overlay/src/default-stop-marker.js
> +    const userFacingId = code || id.split(":")[1];
Nice!

2022-03-15 17:09 UTC, merged