fix: support OTP2 scooter responses
opentripplanner/otp-ui pull request #400
Opened 2022-05-10 15:04 UTC by miles-grant-ibigroup

OTP2 changes how scooters are represented. This PR aims to fully support OTP2 scooter responses

2022-05-25 18:25 UTC, daniel-heppner-ibigroup approved these changes
LGTM

2022-05-25 18:37 UTC, miles-grant-ibigroup commented on packages/core-utils/src/map.ts
> +      } else if (!fromPlaceId) {
to my understanding, without the `if` the clause is effected directly by the `leg.mode === "CAR"` `if` above it

2022-05-25 18:38 UTC, miles-grant-ibigroup commented
I'll assign to @binh-dam-ibigroup once I fix the merge conflict

2022-05-25 20:41 UTC, miles-grant-ibigroup commented on packages/core-utils/src/map.ts
> +          toPlaceId = `escooter_rent_station_${leg.to.bikeShareId}`;
In OTP2 they are the same which is why this went unnoticed! But consistency is good, so I've used `bikeShareId` in the from id

2022-05-25 20:47 UTC, miles-grant-ibigroup commented on packages/core-utils/src/map.ts
> +        // OTP1 Scooter case
Moved in 2b6cb62c

2022-05-25 20:47 UTC, miles-grant-ibigroup commented on packages/core-utils/src/map.ts
> +          toPlaceId = `escooter_rent_station_${leg.to.bikeShareId}`;
2b6cb62c

2022-05-25 22:16 UTC, binh-dam-ibigroup commented on packages/itinerary-body/i18n/en-US.yml
> +      SCOOTER {Ride}
I think there should be a story involving an OTP2 scooter rental.

2022-05-25 22:21 UTC, binh-dam-ibigroup requested changes
Could you add a story to ItineraryBody with an OTP2 scooter rental, please?

2022-05-26 18:50 UTC, binh-dam-ibigroup approved these changes

2022-05-26 19:34 UTC, merged