chore(trip-details:deps): Remove types pkg dep
opentripplanner/otp-ui pull request #404
Opened 2022-05-20 14:08 UTC by binh-dam-ibigroup

This fixes the build that's reported broken after merging #403 (it probably became broken after merging #367).

2022-05-20 14:14 UTC, miles-grant-ibigroup requested changes
I was able to fix this like so: https://github.com/opentripplanner/otp-ui/pull/400/commits/3a177cba3a6f18d9eede322dd7f93440281c9519#diff-0d962559c234d86f1bdbc98f27ab0f840d7f64f1813d58835fd0443d1df3ae57L20

Does removing the dependency really not affect the build?

2022-05-20 14:18 UTC, binh-dam-ibigroup commented
> I was able to fix this like so: [3a177cb#diff-0d962559c234d86f1bdbc98f27ab0f840d7f64f1813d58835fd0443d1df3ae57L20](https://github.com/opentripplanner/otp-ui/commit/3a177cba3a6f18d9eede322dd7f93440281c9519#diff-0d962559c234d86f1bdbc98f27ab0f840d7f64f1813d58835fd0443d1df3ae57L20)
> 
> Does removing the dependency really not affect the build?

Maybe, but the same thing will happen at the next breaking change.

2022-05-20 14:19 UTC, miles-grant-ibigroup approved these changes
If this doesn't affect the build or the snapshots then I guess I approve!

2022-05-20 19:26 UTC, miles-grant-ibigroup requested changes
I think upgrading the package is the way to go

2022-05-20 20:29 UTC, binh-dam-ibigroup commented
> 30d2845

Lol I readded the ref in https://github.com/opentripplanner/otp-ui/pull/404/commits/30d284545af5aeac8a125bc5232c4501459dcbac and that is not working!

2022-05-20 20:31 UTC, miles-grant-ibigroup commented
I thiiiink you might just have to update the snapshots! I had the same problem when I patched this in all my PRs but I'm not sure why the types package changes the snapshots I will be honest

2022-05-23 16:34 UTC, miles-grant-ibigroup approved these changes

2022-05-25 23:11 UTC, daniel-heppner-ibigroup approved these changes

2022-05-26 12:23 UTC, merged