Improve Itinerary and CO2 Types
opentripplanner/otp-ui pull request #528
Opened 2023-01-11 18:29 UTC by daniel-heppner-ibigroup

This PR adds a new type for mass units, and also a "looser" Itinerary type that makes all fields optional except legs, since in most places that is the only property we need. This will make Typescript happier when we are making "fake" itineraries in OTP-RR and in testing.

2023-01-11 20:36 UTC, miles-grant-ibigroup requested changes
Not the hugest fan of the second Itinerary type just for this one use case -- some advanced typescript going on as well. Is there no way to make the itinerary type have optional fields?

2023-01-11 20:36 UTC, miles-grant-ibigroup commented on packages/types/src/index.ts
> +export type ItineraryOnlyLegsRequired = Partial<Itinerary> &
super nitpick: can we put this on one line?

2023-01-12 00:03 UTC, daniel-heppner-ibigroup commented
What do you mean by one use case? It's used like this everywhere in the itinerary core utils file. I wasn't sure about modifying the Itinerary type to make all the fields permanently optional, it would probably break a lot of other stuff. @miles-grant-ibigroup

2023-01-12 11:34 UTC, miles-grant-ibigroup commented
I thought we were making this change to make the tests work with typescript! In that case I'd either rename the new type to make it clear what it's for or try to unify the types.

2023-01-19 00:04 UTC, daniel-heppner-ibigroup commented
> I thought we were making this change to make the tests work with typescript! In that case I'd either rename the new type to make it clear what it's for or try to unify the types.

Let me explain what's going on a bit better here; I needed a more relaxed type for the calculateEmissions function, since when there is no driving itinerary in OTP, we generate a fake one that only contains the legs property. Typescript isn't happy about this object not containing any other Itinerary properties, but we don't actually need those. That's what I made this type for. Then I realized that actually, none of these functions require anything besides the legs, so I just applied the type to all of them. 

I can name it something else, but I thought it would be good just name it something super obvious.

2023-01-19 14:42 UTC, miles-grant-ibigroup commented
Thanks for that explanation! This all makes sense to me. I don't have a better alternative name right now, so will defer to the second reviewer

2023-01-20 15:48 UTC, binh-dam-ibigroup approved these changes
LGTM

2023-01-20 15:48 UTC, binh-dam-ibigroup commented on packages/trip-details/src/types.ts
> +import type { FareDetails, Money, Itinerary, Leg, Fare, MassUnitOption, } from "@opentripplanner/types";
Sort imports, remove trailing comma

2023-01-27 20:09 UTC, merged