Trip form a11y
opentripplanner/otp-ui pull request #557
Opened 2023-03-09 17:24 UTC by demory

Adds accessibility support (screenreader / keyboard navigation) to the DateTimeSelector and SettingsSelectorPanel components and subcomponents.

2023-03-09 19:07 UTC, binh-dam-ibigroup requested changes
A few minor changes, and please include a commitizen `fix` commit, so that a new version number can be released.

2023-03-09 19:07 UTC, binh-dam-ibigroup commented on packages/trip-form/src/SubmodeSelector/index.tsx
> +      {label && <LabelType aria-hidden="true">{label}</LabelType>}
This label is unused by any input element, so I would convert to a span:
```suggestion
      {label && <LabelType aria-hidden="true" as="span">{label}</LabelType>}
```

2023-03-13 18:27 UTC, binh-dam-ibigroup approved these changes
Sorry it took a while to clear all a11y test errors. Should be good to go with our latest changes.

2023-03-13 21:21 UTC, amy-corson-ibigroup approved these changes
Two small typos, otherwise LGTM!

2023-03-13 21:21 UTC, amy-corson-ibigroup commented on packages/trip-form/src/components.story.tsx
> +// This error may be raised by us rendering two copies of eagh story.
```suggestion
// This error may be raised by us rendering two copies of each story.
```

2023-03-13 21:21 UTC, amy-corson-ibigroup commented on packages/trip-form/src/components.story.tsx
> +// This error may be raised by us rendering two copies of eagh story.
```suggestion
// This error may be raised by us rendering two copies of each story.
```

2023-03-14 12:30 UTC, merged