Remove calories from trip details
opentripplanner/otp-ui pull request #570
Opened 2023-04-11 22:29 UTC by amy-corson-ibigroup

Fully removes calorie counts, associated methods, and i18n strings.

Potentially replaced by "steps" or "minutes active" down the line.

2023-04-21 14:02 UTC, binh-dam-ibigroup requested changes
I recommend not changing anything in core-utils.
Please fill in intl content for the desired languages.

I would prefer the activity time to be a new feature instead of a breaking change, but if people feel strongly about removing calories, please add a breaking change commit.

2023-04-28 18:59 UTC, binh-dam-ibigroup requested changes
Please see the cleanup and missing translation comments. I would suggest making the core-utils changes in a separate PR.

2023-04-28 18:59 UTC, binh-dam-ibigroup commented on packages/core-utils/src/itinerary.ts
> -): {
Caution: If this change is left in this PR, the trip-details package will still reference the currently used core-utils (8.1.1), even though core-utils version 9.0.0 will be released. This should not break the trip-details package.

2023-04-28 18:59 UTC, binh-dam-ibigroup commented on packages/trip-details/src/index.tsx
> +  TimeActiveDetailsProps
Sort imports.

2023-04-28 18:59 UTC, binh-dam-ibigroup commented on packages/trip-details/src/TripDetails.story.tsx
> +    TimeActiveDetails: CustomTimeActiveDetails,
Sort attributes.

2023-04-28 18:59 UTC, binh-dam-ibigroup commented on packages/trip-details/src/TripDetails.story.tsx
> +        TimeActiveDetails={TimeActiveDetails}
Sort props.

2023-04-28 18:59 UTC, binh-dam-ibigroup commented on packages/trip-details/src/TripDetails.story.tsx
> +      TimeActiveDetails,
Sort attributes.

2023-04-28 18:59 UTC, binh-dam-ibigroup commented on packages/trip-details/src/TripDetails.story.tsx
> +  TimeActiveDetailsProps,
Sort imports.

2023-04-28 18:59 UTC, binh-dam-ibigroup commented on packages/trip-details/src/index.tsx
> +  TimeActiveDetails = DefaultTimeActiveDetails,
Sort props

2023-04-28 18:59 UTC, binh-dam-ibigroup commented on packages/trip-details/src/types.ts
> +  TimeActiveDetails?: React.ElementType<TimeActiveDetailsProps>;
Sort props.

2023-04-28 18:59 UTC, binh-dam-ibigroup commented on packages/trip-details/i18n/en-US.yml
> +    timeActiveDescription: >
`timeActiveDescription` needs to be provided in the other languages.

2023-05-03 21:25 UTC, amy-corson-ibigroup commented on packages/core-utils/src/itinerary.ts
> -): {
Thanks for explaining this! I've re-added this function to core-utils.

2023-05-03 21:45 UTC, binh-dam-ibigroup commented on packages/core-utils/src/itinerary.ts
> -): {
Hmm... Commit https://github.com/opentripplanner/otp-ui/pull/570/commits/bdf0531725443610764472af246826d2d192a917 was not reverted (using a commitizen `revert` commit), so in order to not gamble on the outcome of this PR, I would recommend you create a new PR with just the changes to the `trip-details` package.

2023-05-03 22:27 UTC, amy-corson-ibigroup commented
Closed in favor of #580

2023-05-03 22:27 UTC, closed without merging