Replace Calories with Minutes Active in Trip Details
opentripplanner/otp-ui pull request #580
Opened 2023-05-03 22:26 UTC by amy-corson-ibigroup

Removes calorie counts and repurposes all methods with "Time Active" which combines time spent biking and walking to reflect the total number of minutes spent active in the trip duration.

BREAKING CHANGE: Calories removed and replaced by minutes active

![image](https://user-images.githubusercontent.com/115499534/236063654-a89b07bf-dc0a-48f0-9f5d-3bb64a43499c.png)

2023-05-04 16:20 UTC, binh-dam-ibigroup commented on packages/trip-details/src/index.tsx
> +  const walkDuration = Math.round(walkDurationSeconds / 60);
Rename to `bikeMinutes`, `walkMinutes`.

2023-05-04 16:20 UTC, binh-dam-ibigroup commented on packages/trip-details/src/index.tsx
> +  walkDuration
We previously explicitly put the units in the prop names to remove any ambiguity, so `bikeDuration` and `walkDuration` should be renamed to `bikeMinutes` and `walkMinutes`.

2023-05-04 16:30 UTC, binh-dam-ibigroup commented
@amy-corson-ibigroup Remember to fix the snapshots.

2023-05-05 14:04 UTC, miles-grant-ibigroup requested changes
Great refactor! Just a few nitpicks

2023-05-05 14:04 UTC, miles-grant-ibigroup commented on packages/trip-details/src/index.tsx
> +  });
This can probably be cleaned up into 2 reducers (maybe even with a shared method body) but for now a TODO to refactor this is probably fine

2023-05-05 14:04 UTC, miles-grant-ibigroup commented on packages/trip-details/i18n/en-US.yml
> +    minutesActive: "Time Spent Active: {minutes, plural, one {# minute} other {# minutes}}"
The number of minutes needs to be bold to match the other rows

2023-05-05 15:09 UTC, amy-corson-ibigroup commented on packages/trip-details/__mocks__/custom-english-messages.yml
> +    tncFare: Pay <strong>{minTNCFare}-{maxTNCFare}</strong> to {companies}
The pre-commit hooks automatically alphabetize these!

2023-05-05 16:27 UTC, miles-grant-ibigroup approved these changes
Code looks great! Just need to fix this spacing issue and then we're good to go! <img width="283" alt="Screenshot 2023-05-05 at 12 27 23 PM" src="https://user-images.githubusercontent.com/86619099/236514297-f70e73d4-53dd-4f54-82ab-04098eeae8f9.png">

2023-05-08 16:26 UTC, merged