Fare Table comaptibility with OTP2 FareProduct API
opentripplanner/otp-ui pull request #612
Opened 2023-07-03 20:01 UTC by daniel-heppner-ibigroup

2023-07-07 15:02 UTC, miles-grant-ibigroup approved these changes
Good work! There are a few spots that are ripe for future refactoring but given how many consumers are excited for fares to come back I think this feels good

2023-07-10 17:49 UTC, binh-dam-ibigroup requested changes
Please first create two separate PRs for these packages:
- types
- core-utils

2023-07-10 17:51 UTC, miles-grant-ibigroup commented
Because of some internal dependency complications, we had to undo this change. We instead will have to merge all this first and then create a follow up PR that removes depending on alpha versions

2023-07-10 17:58 UTC, binh-dam-ibigroup commented
> Please first create two separate PRs for these packages:
> 
> * types
> * core-utils

The types PR should contain a breaking change commit.

2023-07-10 18:05 UTC, binh-dam-ibigroup commented
> Because of some internal dependency complications, we had to undo this change. We instead will have to merge all this first and then create a follow up PR that removes depending on alpha versions

Ok. Still needs a breaking change to the types package.

2023-07-10 18:58 UTC, binh-dam-ibigroup reviewed
See comment for types and core-utils packages (more comments to come)

2023-07-10 18:58 UTC, binh-dam-ibigroup commented on packages/types/src/index.ts
> +  mediumId: string;
Sort props.

2023-07-10 18:58 UTC, binh-dam-ibigroup commented on packages/types/src/index.ts
> +  medium?: {
Sort props.

2023-07-10 18:58 UTC, binh-dam-ibigroup commented on packages/types/src/index.ts
> +  fareProducts?: Array<{ id: string; product: FareProduct }>;
```suggestion
  fareProducts?: { id: string; product: FareProduct }[];
```

2023-07-10 18:58 UTC, binh-dam-ibigroup commented on packages/types/src/index.ts
> +  fareProducts?: Array<{ id: string; product: FareProduct }>;
Also sort props.

2023-07-10 18:58 UTC, binh-dam-ibigroup commented on packages/core-utils/src/__tests__/__snapshots__/itinerary.js.snap
> +}
The description of the test does not match the output, which doesn't contain the total cost of an itinerary. Maybe inline the result into the test itself.

2023-07-10 18:58 UTC, binh-dam-ibigroup commented on packages/core-utils/src/__tests__/itinerary.js
> +            name: "rideCost",
Sort attributes (multiple instances).

2023-07-10 18:58 UTC, binh-dam-ibigroup commented on packages/core-utils/src/__tests__/itinerary.js
> +          product: {
The `id` attribute is missing (2 instances).

2023-07-10 18:59 UTC, binh-dam-ibigroup commented on packages/core-utils/src/itinerary.ts
> +): { price?: Money; transferAmount?: Money | undefined } {
Pl address this comment.

2023-07-10 20:08 UTC, binh-dam-ibigroup requested changes
Needs a few more breaking change commits and some cleanup. Also, fares are no longer shown for the regular transit legs and for http://localhost:5555/?path=/story/tripdetails--fare-components-itinerary&globals=locale:en-US and http://localhost:5555/?path=/story/itinerarybody-otp-react-redux--individual-leg-fare-components&globals=locale:en-US, so either the fares should be shown, or the story title/contents should be updated.

2023-07-10 20:08 UTC, binh-dam-ibigroup commented on packages/trip-details/src/utils.tsx
> +export function boldText(contents: ReactElement | string): ReactElement {
```
export function boldText(contents: ReactNode): ReactElement {
```
(with proper import)

2023-07-10 23:28 UTC, daniel-heppner-ibigroup commented on packages/itinerary-body/src/TransitLegBody/index.tsx
> +      defaultFareSelector
no, maybe we could add one but I am not sure what it would be.

2023-07-11 01:10 UTC, daniel-heppner-ibigroup commented on packages/itinerary-body/src/TransitLegBody/index.tsx
> +                {legCost && (
No, that was a mistake.

2023-07-11 01:15 UTC, daniel-heppner-ibigroup commented on packages/itinerary-body/src/TransitLegBody/index.tsx
> +                {legCost && (
I did some work to fix the fares displaying in the itinerary body. Lots of prop drilling, we should return to clean this up.

2023-07-11 01:16 UTC, daniel-heppner-ibigroup commented on packages/itinerary-body/src/TransitLegBody/index.tsx
> +                {legCost && (
Also includes breaking change for itinerary-body.

2023-07-11 01:16 UTC, daniel-heppner-ibigroup commented on packages/itinerary-body/src/ItineraryBody/index.tsx
> -  showRouteFares,
removed and breaking change added in [48bdcc4](https://github.com/opentripplanner/otp-ui/pull/612/commits/48bdcc41c1d6286c4b569c070e9758a225d70f1e).

2023-07-12 14:17 UTC, binh-dam-ibigroup approved these changes
Much cleaner now. See the few more items. Thanks for the changes!

2023-07-12 14:17 UTC, binh-dam-ibigroup commented on packages/itinerary-body/src/stories/OtpRrItineraryBody.story.tsx
> +  defaultFareSelector?: FareProductSelector;
Sort props.

2023-07-12 14:17 UTC, binh-dam-ibigroup commented on packages/itinerary-body/src/stories/OtpRrItineraryBody.story.tsx
> +    defaultFareSelector={{
Sort props

2023-07-12 14:17 UTC, binh-dam-ibigroup commented on packages/trip-details/src/TripDetails.story.tsx
> -export const BikeTransitBikeItinerary = makeStory({
Thanks for removing the irrelevant stories!

2023-07-12 23:56 UTC, merged