refactor: pass otp2 custom config colors
opentripplanner/otp-ui pull request #623
Opened 2023-07-20 17:28 UTC by amy-corson-ibigroup

Pass custom config color into OTP2 layers to override defaults.

<img width="394" alt="image" src="https://github.com/opentripplanner/otp-ui/assets/115499534/a97336a4-8fb6-4d0c-a48a-62b7a85c9c2c">

2023-07-21 18:17 UTC, daniel-heppner-ibigroup approved these changes
I was going to ask you to make the story use this, but it appears that the story is broken entirely. Could you maybe add a todo in the story to use this new parameter in it once we have fixed the story?

2023-07-24 16:56 UTC, amy-corson-ibigroup commented on packages/otp2-tile-overlay/src/index.tsx
> +  console.log(layers)
Hmm I guess

2023-07-24 22:37 UTC, amy-corson-ibigroup commented on packages/otp2-tile-overlay/src/index.tsx
> +  console.log(layers)
Fixed in [18c45fa](https://github.com/opentripplanner/otp-ui/pull/623/commits/18c45fa00431751928cee72815531bc169dff749) along with the todo!

2023-07-25 10:09 UTC, miles-grant-ibigroup requested changes
One small but important change and then I think we're good to go!

2023-07-25 10:09 UTC, miles-grant-ibigroup commented on packages/otp2-tile-overlay/src/util.ts
> +export const LAYER_PAINT = (color?: string): any => {
This should be renamed since it's no longer a constant 
```suggestion
export const generateLayerPaint = (color?: string): any => {
```

2023-07-25 19:35 UTC, merged