Walk Reluctance Checkbox + Walk Speed Dropdown
opentripplanner/otp-ui pull request #631
Opened 2023-07-28 22:29 UTC by amy-corson-ibigroup

Co-authored-by: Miles Grant <miles-grant-ibigroup@users.noreply.github.com>
Co-authored-by: Daniel Heppner <daniel-heppner-ibigroup@users.noreply.github.com>

2023-08-07 17:01 UTC, daniel-heppner-ibigroup approved these changes
per discussion, let's remove the override thing.

2023-08-07 21:09 UTC, amy-corson-ibigroup commented on packages/trip-form/i18n/en-US.yml
> +      walkReluctance-label: Avoid Walking?
do we hate

2023-08-09 13:03 UTC, miles-grant-ibigroup commented on packages/trip-form/i18n/en-US.yml
> +      walkReluctance-label: Avoid Walking?
yes

2023-08-09 13:16 UTC, miles-grant-ibigroup requested changes
Great fix, really clean! A little confused about the `subsettingOverrides` and the question mark.

2023-08-09 21:23 UTC, amy-corson-ibigroup commented on packages/trip-form/i18n/en-US.yml
> +      walkReluctance-label: Avoid Walking?
wow...

2023-08-09 21:29 UTC, amy-corson-ibigroup commented on packages/trip-form/src/MetroModeSelector/index.tsx
> +  subsettingOverrides?: Array<ModeSetting>;
No! Just missed taking out all the prop drilling in [ab1cae8](https://github.com/opentripplanner/otp-ui/pull/631/commits/ab1cae8087f800be8959a2fe205650c2178f9902)! Removed in [f26ce83](https://github.com/opentripplanner/otp-ui/pull/631/commits/f26ce83d9d46a88ea9e3f0bfe9b85c640b8b39c7)

2023-08-10 16:19 UTC, miles-grant-ibigroup requested changes
Just one more small thing to remove and then if you could please merge master into this branch so we have a cleaner merge we should be good to go!

2023-08-10 16:19 UTC, miles-grant-ibigroup commented on packages/trip-form/src/MetroModeSelector/index.tsx
> +   */
I think you forgot to take out this comment!

2023-08-10 17:37 UTC, miles-grant-ibigroup approved these changes
Looks wonderful thanks!

2023-08-10 19:29 UTC, merged