Cleanup yarn.lock, Remove IE11
opentripplanner/otp-ui pull request #657
Opened 2023-09-14 18:04 UTC by miles-grant-ibigroup

This PR removes IE11 support. OTP-UI has not worked with IE11 for a while now, but for some reason we still had some compatibility code in there. 

This PR also cleans some other dependencies and runs yarn deduplicate, which should help with bundle sizes

2023-09-14 19:37 UTC, AdrianaCeric approved these changes
Internet Explorer 11 is so vintage. I think there is just a duplicate mock to sort out

2023-09-15 12:39 UTC, binh-dam-ibigroup requested changes
Why are tests failing?

2023-09-15 12:39 UTC, binh-dam-ibigroup commented on packages/core-utils/src/ui.ts
> -export function isIE(): boolean {
Although this is a breaking change, we can market that IE is no longer supported as of core-utils 11.0.0.

2023-09-15 17:51 UTC, miles-grant-ibigroup commented
Looks like deduplicate is causing a package to update that is breaking story shot. Will revert

2023-09-15 19:11 UTC, binh-dam-ibigroup approved these changes

2023-09-15 19:13 UTC, merged