Banned routes generator
opentripplanner/otp-ui pull request #699
Opened 2024-01-09 23:06 UTC by amy-corson-ibigroup

In cases where there are route mode overrides in the config, we'll use the banned parameter to exclude routes under a custom submode. This adds a util function to generate a list of banned routes based on the mode settings and route mode overrides.

2024-01-24 18:16 UTC, daniel-heppner-ibigroup requested changes
A few things that need to be fixed here

2024-01-24 18:16 UTC, daniel-heppner-ibigroup commented on packages/trip-form/src/MetroModeSelector/utils.ts
> +        const modeName = cur.modeOverride || cur.addTransportMode.mode;
I don't think this property exists, please remove it. Only check for `addTransportMode.mode`.

2024-01-24 23:42 UTC, daniel-heppner-ibigroup approved these changes
I've changed this around to how I think it should work. Let me know what you think! 
The reason I prefer this is because it doesn't change the meaning of any existing properties.

2024-01-29 19:55 UTC, amy-corson-ibigroup commented
@daniel-heppner-ibigroup Makes sense & much cleaner, thank you!!

2024-01-29 20:50 UTC, miles-grant-ibigroup approved these changes
This is such a clean solution for such a wild feature! Great work

2024-01-30 18:53 UTC, merged