fix(itinerary-body): Show accessibility label if score is 0
opentripplanner/otp-ui pull request #701
Opened 2024-01-12 21:27 UTC by amy-corson-ibigroup

Fixes an issue where if the accessibility score is 0, the badge was not displaying.

2024-01-12 21:31 UTC, binh-dam-ibigroup approved these changes

2024-01-16 15:12 UTC, miles-grant-ibigroup requested changes
Does this work? Might be cleaner

2024-01-16 15:12 UTC, miles-grant-ibigroup commented on packages/itinerary-body/src/ItineraryBody/place-row.tsx
> +          leg.accessibilityScore > -1 && (
```suggestion
          !(leg.accessibilityScore === undefined) && (
```

2024-01-17 19:42 UTC, amy-corson-ibigroup commented on packages/itinerary-body/src/ItineraryBody/place-row.tsx
> +          leg.accessibilityScore > -1 && (
Yep makes sense!

2024-01-18 15:47 UTC, miles-grant-ibigroup approved these changes
Looks great! approved pending updated tests

2024-01-18 22:39 UTC, merged