feat(core-utils): remove old query params handled by new mode selector
opentripplanner/otp-ui pull request #712
Opened 2024-02-08 22:54 UTC by daniel-heppner-ibigroup

This PR removes a bunch of old query parameters that are no longer needed here, either because they're now directly managed by the mode selector (mode settings) or because they're no longer supported by OTP (like max walk distance).

2024-02-08 23:03 UTC, binh-dam-ibigroup requested changes
I think you should add a breaking change commit (or redo the PR with that commit being breaking change).

2024-02-23 20:59 UTC, daniel-heppner-ibigroup commented
Lost track of this PR for a bit, but I force pushed the breaking change commit. If you had this branch cloned, you'll need to delete it and pull it again. Or maybe force pull.

2024-02-28 16:24 UTC, binh-dam-ibigroup requested changes
Can we delete more old params and get rid of the old routing types?

2024-02-28 16:24 UTC, binh-dam-ibigroup commented on packages/core-utils/src/query-params.js
The comment on lines 1-2 doesn't apply anymore and can be removed.

2024-02-28 16:24 UTC, binh-dam-ibigroup commented on packages/core-utils/src/query-params.js
We can probably remove the profile-only params that have `routingTypes: ["PROFILE"]` (these are holdouts from before my time) such as `startTime`, `endTime`.

2024-02-28 16:24 UTC, binh-dam-ibigroup commented on packages/core-utils/src/query-params.js
In the same vein, I think we can get rid of `routingTypes`, `profileRewrite` alltogether. Thoughts?

2024-02-28 16:24 UTC, binh-dam-ibigroup commented on packages/core-utils/src/query-params.js
I have never seen `showIntermediateStops`, `otherThanPreferredRoutesPenalty` in action, and have not seen `ignoreRealtimeUpdates`, `companies`,  in action in years, so that one can be deleted too.

2024-02-28 16:24 UTC, binh-dam-ibigroup commented on packages/core-utils/src/query-params.js
>      /* optimize -- how to optimize a trip (non-bike, non-micromobility trips) */
Are `optimize` and `optimizeBike` still in use?

2024-02-28 16:24 UTC, binh-dam-ibigroup commented on packages/core-utils/src/query-params.js
>      name: "watts",
Are the device power settings (`watts`) still in use?

2024-02-28 16:24 UTC, binh-dam-ibigroup commented on packages/core-utils/src/query-params.js
Is `numItineraries` supposed to come from config for each mode combination later on? If so, it can be removed from here.

2024-02-28 16:24 UTC, binh-dam-ibigroup commented on packages/core-utils/src/query-params.js
How about all the params below `otherThanPreferredRoutesPenalty`?

2024-03-06 20:36 UTC, daniel-heppner-ibigroup commented on packages/core-utils/src/query-params.js
I think the file should still be removed entirely, but probably not because of settingsselector anymore.

2024-03-06 20:36 UTC, daniel-heppner-ibigroup commented on packages/core-utils/src/query-params.js
Yes! I was worried someone was using those, like TriMet, but I think you're right that we can remove them.

2024-03-10 00:36 UTC, daniel-heppner-ibigroup commented
I deleted a lot more of the query parameters, but that caused some problems in the SettingsSelectorPanel, which is still being used in some instances and we aren't ready to fully deprecate, even with a breaking change. So I had to revert those changes, I think at this point we can merge this to fix the original bug.

2024-03-15 14:09 UTC, binh-dam-ibigroup requested changes
Main ask is to remove the deleted query params from `defaultParams`. But should we also remove query parameters not supported by the mode selector?

2024-03-19 15:49 UTC, daniel-heppner-ibigroup commented
I'm closing the PR, let's try again without all the jank from the revert commits.

2024-03-19 15:49 UTC, closed without merging