Fix Map Popups (and focus traps)
opentripplanner/otp-ui pull request #777
Opened 2024-09-16 18:47 UTC by amy-corson-ibigroup

Fixes IDs that are breaking due to stop codes, passes `closePopup` to `MapPopup` through `otp2-tile-layer`

2024-09-17 12:22 UTC, miles-grant-ibigroup requested changes
Small but crucial nitpick

2024-09-17 12:22 UTC, miles-grant-ibigroup commented on packages/map-popup/src/index.tsx
> +export function MapPopup({ closePopup = () => null, configCompanies, entity, getEntityName, setLocation, setViewedStop }: Props): JSX.Element {
```suggestion
export function MapPopup({ closePopup = () => void, configCompanies, entity, getEntityName, setLocation, setViewedStop }: Props): JSX.Element {
```
Should this be void instead?

2024-09-17 13:24 UTC, amy-corson-ibigroup commented on packages/map-popup/src/index.tsx
> +export function MapPopup({ closePopup = () => null, configCompanies, entity, getEntityName, setLocation, setViewedStop }: Props): JSX.Element {
This isn't a type it's a default!

2024-09-17 13:37 UTC, miles-grant-ibigroup commented on packages/map-popup/src/index.tsx
> +export function MapPopup({ closePopup = () => null, configCompanies, entity, getEntityName, setLocation, setViewedStop }: Props): JSX.Element {
We have a noOp function you can import

2024-09-18 14:23 UTC, miles-grant-ibigroup approved these changes
This looks great! But CI seems insanely broken? What's going on

2024-09-18 19:41 UTC, josh-willis-arcadis approved these changes

2024-09-18 19:52 UTC, merged