Update Date/Time Selector
opentripplanner/otp-ui pull request #793
Opened 2024-11-04 18:52 UTC by amy-corson-ibigroup

2024-11-14 21:41 UTC, miles-grant-ibigroup requested changes
We definitely need this to be a breaking change! Please add a breaking change commit. Stories look great! Haven't looked at the code yet

2024-12-05 20:41 UTC, miles-grant-ibigroup requested changes
First round of fixes! There's some layout problems in some contexts and some code cleanup possible too

2024-12-05 20:41 UTC, miles-grant-ibigroup commented on packages/trip-form/src/DateTimeSelector/index.tsx
> +        <Dropdown alignMenuLeft id="date-time-depart-arrive" text={departureOptions.find(opt => opt.isSelected).text} buttonStyle={{ backgroundColor: S.baseColor() || blue[900], borderRadius: "3px 0p
Can we make the default gray instead of blue?

2024-12-05 20:41 UTC, miles-grant-ibigroup commented on packages/trip-form/src/DateTimeSelector/index.tsx
> +        <Dropdown alignMenuLeft id="date-time-depart-arrive" text={departureOptions.find(opt => opt.isSelected).text} buttonStyle={{ backgroundColor: S.baseColor() || blue[900], borderRadius: "3px 0p
Also some of these values are pretty fixed and are causing layout problems in some implementations. Any way we can make this more reactive to its environment?

2024-12-05 20:41 UTC, miles-grant-ibigroup commented on packages/trip-form/src/DateTimeSelector/index.tsx
> +  });
This works but it's pretty inefficient... Anyway we can replace/generate `isSelected` when we're iterating through the array anyway?

2025-01-27 19:42 UTC, amy-corson-ibigroup commented on packages/trip-form/src/DateTimeSelector/index.tsx
> +        <Dropdown alignMenuLeft id="date-time-depart-arrive" text={departureOptions.find(opt => opt.isSelected).text} buttonStyle={{ backgroundColor: S.baseColor() || blue[900], borderRadius: "3px 0p
We approved the designs with the blue, also I think generally we've been using blue[900] to represent the styled base color, so using grey seems a little inconsistent.

Can you elaborate on which values are causing issues? I'm seeing the height but a lot of form elements have fixed heights. Took out the padding though because it was redundant!!

2025-01-27 19:43 UTC, amy-corson-ibigroup commented on packages/trip-form/src/DateTimeSelector/index.tsx
> +  });
Added! We do have to add the check in a few places, let me know what you think!

2025-01-27 19:47 UTC, miles-grant-ibigroup commented on packages/trip-form/src/DateTimeSelector/index.tsx
> +        <Dropdown alignMenuLeft id="date-time-depart-arrive" text={departureOptions.find(opt => opt.isSelected).text} buttonStyle={{ backgroundColor: S.baseColor() || blue[900], borderRadius: "3px 0p
Try with any non-blue config! The blue looks very out of place. As for getting render issues try loading a config that was migrated from the batch ui and then resize the window

2025-01-31 15:27 UTC, miles-grant-ibigroup requested changes
Mostly looking good, just the blue is still bothering me. Still have to do some more integration tests as well

2025-01-31 15:27 UTC, miles-grant-ibigroup commented on packages/trip-form/src/DateTimeSelector/index.tsx
> +        <Dropdown alignMenuLeft id="date-time-depart-arrive" text={departureOptions.find(opt => opt.type === departArrive).text} buttonStyle={{ backgroundColor: S.baseColor() || blue[900], borderRadi
We can probably set extract `S.baseColor() || blue/gray`?

2025-02-06 15:18 UTC, miles-grant-ibigroup approved these changes
Code looks good! Haven't been able to test otp-rr integration yet let's hope that goes well

2025-02-06 15:18 UTC, miles-grant-ibigroup commented on packages/trip-form/src/DateTimeSelector/index.tsx
> +      if (departArrive === "NOW") {
nitpick: if departureOptions were an enum then we could reuse that instead of using a magic string

2025-02-11 19:09 UTC, amy-corson-ibigroup commented on packages/trip-form/src/DateTimeSelector/index.tsx
> +      if (departArrive === "NOW") {
Would you change `departureOptions` to 
```
departureOptions = {
now: "NOW"
etc
```
And then render the text strings dynamically?

2025-02-13 17:56 UTC, miles-grant-ibigroup commented on packages/trip-form/src/DateTimeSelector/index.tsx
> +      if (departArrive === "NOW") {
yes! but it's such a nitpick

2025-02-19 14:15 UTC, binh-dam-ibigroup approved these changes
A few CSS tweaks, but seems fine otherwise.

2025-02-19 14:15 UTC, binh-dam-ibigroup commented on packages/trip-form/src/types.ts
> +  { baseColor?: string | undefined }
Remove `undefined` (`undefined` is implied in the `?:` syntax).

```suggestion
  { baseColor?: string }
```

2025-02-19 14:15 UTC, binh-dam-ibigroup commented on packages/trip-form/src/styled.ts
> +export const DateTimeSelector: DateTimeSelectorAndSubComponents = styled.div<{ baseColor: string | undefined }>`
```suggestion
export const DateTimeSelector: DateTimeSelectorAndSubComponents = styled.div<{ baseColor?: string }>`
```

2025-02-19 14:16 UTC, binh-dam-ibigroup requested changes
Actually, you need to update the snapshots.

2025-02-24 17:02 UTC, binh-dam-ibigroup approved these changes
Two small styling things but good to go nonetheless

2025-02-24 17:02 UTC, binh-dam-ibigroup commented on packages/trip-form/src/DateTimeSelector/index.tsx
> +        <Dropdown alignMenuLeft id="date-time-depart-arrive" text={departureOptions.find(opt => opt.type === departArrive).text} buttonStyle={buttonStyle}>
Breakup this long line.

2025-04-22 18:46 UTC, amy-corson-ibigroup commented
This is being closed in favor of a different design approach

2025-04-22 18:46 UTC, closed without merging