Swap out yarn for pnpm
opentripplanner/otp-ui pull request #795
Opened 2024-11-12 00:44 UTC by daniel-heppner-ibigroup

Yarn 1 has been unsupported for a while, with the last update 3 years ago. The biggest problem with running such an old version is that we are missing out on the more ergonomic ways of referencing internal dependencies. 

Instead of needing to stay on top of internal dependency versions, we can now just reference `workspace:*` as our version number for any internal dependency.

2024-12-03 18:27 UTC, miles-grant-ibigroup requested changes
Can we have it auto-prepublish again? Also can we make sure that published packages refer to actual package versions and not the workspace things

2025-01-10 20:08 UTC, daniel-heppner-ibigroup commented
From the docs: 
"Before publish, aliases are converted to regular aliased dependencies. The above example will become: "bar": "npm:foo@1.0.0"."
https://pnpm.io/workspaces

2025-01-13 11:58 UTC, daniel-heppner-ibigroup commented
`prepublish` now runs after `install` automatically. Since internal dependencies are symlinked instead of downloaded from npm, this is necessary for things to work properly. I think both of your comments are now addressed.

2025-01-13 16:11 UTC, daniel-heppner-ibigroup commented
It looks like the SVGs are changing in the snapshots because the version of styled icons changed.

<img width="102" alt="image" src="https://github.com/user-attachments/assets/45cde91e-255e-48a4-aa11-ca14d923cac5" />
I'm seeing slight visual differences on them but nothing substantial and not related to the build system.

2025-01-23 19:11 UTC, miles-grant-ibigroup commented
Things are looking much better. Is there any way we can update the yarn prepublish to add a warning about using pnpm instead?

2025-01-28 18:08 UTC, miles-grant-ibigroup requested changes
Do we still need `update-internal-dependencies.js`?

2025-01-28 18:08 UTC, miles-grant-ibigroup commented on README.md
Quite a few missing reference changes in here, especially around workspace package version management

2025-01-29 19:48 UTC, miles-grant-ibigroup commented
Seeing this error when trying to import in otp-rr: `error Couldn't find any versions for "@opentripplanner/map-popup" that matches "workspace:*"\n` +`

`pnpm build` is not working?

2025-01-31 15:36 UTC, miles-grant-ibigroup commented
Can we make a `pack`/`build` script that builds/packs all the packages so that we can test them elsewhere easily? And if we really have to deal with the tarballs then maybe it could spit out a list of the generated tarballs?

2025-02-18 14:29 UTC, miles-grant-ibigroup approved these changes
I think we've gotten this to the point where it's worth trying. I believe in us to resolve any future fallout

2025-02-18 14:32 UTC, miles-grant-ibigroup requested changes
Wait apologies I have to correct myself. I've merged this into the alpha branch and tried to use that alpha package in otp-rr: 
```
➤ yarn                                                                                      09:31:01
yarn install v1.22.10
warning ../package.json: No license field
warning ../../package.json: No license field
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
Couldn't find any versions for "@opentripplanner/building-blocks" that matches "workspace:*"
? Please choose a version of "@opentripplanner/building-blocks" from this list: (Use arrow keys)
❯ 2.1.0
  2.0.0
  1.2.3
  1.2.2
  1.2.1
  1.2.0
  1.1.0
  1.0.3
  1.0.2
  1.0.1
```

2025-02-27 16:23 UTC, miles-grant-ibigroup approved these changes
semrel works great now thanks so much!

2025-03-01 04:49 UTC, daniel-heppner-ibigroup commented
Although semrel was fixed, there was a problem in the build system. Babel could not transpile jsx files, it was only configured for tsx. Took a while to figure out what was going on, but figured it out and now it transpiles both. The latest alpha versions of all packages are from this branch and work in OTP-RR.

2025-03-25 11:28 UTC, daniel-heppner-ibigroup commented
The problem with playwright seems to only be happening in CI, it works fine locally. I'll continue investigating why, but it's hard to debug.

2025-03-25 13:16 UTC, daniel-heppner-ibigroup commented
Sounds like this was a known bug and was fixed in the updated version of test-runner! yay

2025-03-25 18:23 UTC, binh-dam-ibigroup commented on packages/building-blocks/package.json
> +    "@opentripplanner/types": "workspace:*",
Does that mean that, for this case, a new version number for the core-utils or types package also triggers a new version number for building-blocks?

2025-03-26 04:30 UTC, daniel-heppner-ibigroup commented on packages/building-blocks/package.json
> +    "@opentripplanner/types": "workspace:*",
Good catch. This is something I talked about with Miles, since I realized it's a bit of a regression in terms of dev experience. 

semrel runs on the checked in code, looking for which packages have changes. The `workspace:*` gets replaced with a version number in a build step, so semrel won't see that and won't release a new version of dependent packages. 

However, I think it's overall an improvement in dev experience since you can release all the packages at once instead of having to stage your PRs to release each one individually. However, it requires making an arbitrary change in each package to trigger semrel. Using a more modern release/versioning tool would help fix this. 

One thing I just thought of: I should make sure that the version number that pnpm inserts in the `workspace` fields is the number post-semrel bump. For example, if types is 1.0.0 and we release a patch to 1.0.1, then release building-blocks and types together, I need to make sure that the released version of building blocks has 1.0.1 and not 1.0.0.

2025-03-26 20:12 UTC, binh-dam-ibigroup requested changes
Could you resolve the ambiguity between `pnpm bootstrap` and `pnpm install` between the docs and the main package.json, and resolve conflicts please? There are other minor questions and suggested tweaks, but this PRs looks very nice and the changes seems to work. After merging, we'll have to check that package releases still work.

2025-03-26 20:12 UTC, binh-dam-ibigroup commented on packages/trip-details/src/index.tsx
> +function CO2DescriptionLink(contents: ReactNode): ReactElement {
What was the reason for this change?

2025-03-27 15:49 UTC, daniel-heppner-ibigroup commented on packages/base-map/README.md
> +
I think I did this to trigger a release lol

2025-03-27 15:50 UTC, daniel-heppner-ibigroup commented on .github/workflows/node-ci.yml
> +        run: pnpm exec playwright install --with-deps
Not quite, exec doesn't download a package, it just uses the internal binary from the project

2025-03-27 16:36 UTC, daniel-heppner-ibigroup commented on package.json
> +    "semantic-release": "lerna exec --concurrency 1 -- semantic-release -e semantic-release-monorepo -e $(pwd)/release.config.mjs",
I believe the environment variables are no longer auto loaded in the newer version of semantic release. It was confusing to troubleshoot because it also required updates to make it work with pnpm, but I didn't realize the config wasn't even getting loaded anymore.

2025-03-27 16:36 UTC, daniel-heppner-ibigroup commented on README.md
> +- `pnpm install` - This installs all of the packages and links dependent packages together.
I don't think pnpm bootstrap exists, not in their docs. I'll remove the script for it

2025-03-27 16:37 UTC, daniel-heppner-ibigroup commented on package.json
> +    "predev": "pnpm install",
Good point!

2025-03-27 16:37 UTC, daniel-heppner-ibigroup commented on README.md
> + pnpm install
bootstrap doesn't exist

2025-03-27 16:38 UTC, daniel-heppner-ibigroup commented on package.json
> +    "react-intl": "^6.8.4",
Good point. Probably yes, but we can test in OTP RR

2025-03-27 16:57 UTC, daniel-heppner-ibigroup commented on packages/itinerary-body/src/defaults/route-long-name.tsx
> +function toPrefix(contents: ReactNode): ReactElement {
react-intl update required it.

2025-03-27 19:56 UTC, binh-dam-ibigroup commented on package.json
> +    "react-intl": "^6.8.4",
Fortunately, I don't see breaking changes that appear to affect OTP-RR between react-intl 5.x and 6.0: https://github.com/formatjs/formatjs/releases/tag/react-intl%406.0.0

2025-03-27 20:21 UTC, binh-dam-ibigroup approved these changes
Nice changes. `pnpm pack-all` works with OTP-RR which is reassuring. Please update the snaphsots and this PR is good to go.

2025-04-08 17:07 UTC, merged