Set viewed stop from endpoint
opentripplanner/otp-ui pull request #805
Opened 2024-12-31 18:25 UTC by amy-corson-ibigroup

Pass ability to setViewedStop to endpoint layer, so if endpoint is a stop, a user can see it in the stop viewer.

2025-01-08 15:26 UTC, amy-corson-ibigroup commented on packages/endpoints-overlay/src/index.tsx
> +  fromIsStop?: boolean;
No 👍

2025-01-08 15:30 UTC, amy-corson-ibigroup commented on packages/endpoints-overlay/i18n/en-US.yml
> +    viewNearby: View in nearby viewer
The reason for the change is if the endpoint is a stop, we want to be able to view the stop in the nearby viewer. I worry "view nearby transit" might imply you're seeing features AROUND the stop but not the stop itself?

2025-01-08 15:30 UTC, amy-corson-ibigroup commented on packages/endpoints-overlay/src/index.tsx
> +  toIsStop?: boolean;
no 🥰

2025-01-08 15:31 UTC, amy-corson-ibigroup commented on packages/endpoints-overlay/i18n/en-US.yml
> +    viewNearby: View in nearby viewer
There's always the option to pass whether the endpoint is a stop and conditionally render the string, but that's a lot of extra code

2025-01-09 12:08 UTC, miles-grant-ibigroup commented on packages/endpoints-overlay/i18n/en-US.yml
> +    viewNearby: View in nearby viewer
How about "View nearby"?

2025-01-09 12:09 UTC, miles-grant-ibigroup requested changes
Looking much better! Just need to fix that string

2025-01-09 16:25 UTC, miles-grant-ibigroup approved these changes
Terrific!

2025-01-14 17:07 UTC, binh-dam-ibigroup requested changes
Pass the `setViewedStop` action to the existing stories that have the popup, so that devs can see that action's params. Rename a few props.

2025-01-14 17:07 UTC, binh-dam-ibigroup commented on packages/endpoints-overlay/src/EndpointsOverlay.story.tsx
> +export const EndpointsOverlayWithStopLink: ComponentStory<typeof EndpointsOverlay> = () => (
Remove this story. The View Nearby link already appears in story "Endpoint Overlay With User Settings" and "Endpoint Overlay with Unnamed Place". Pass the new `setViewedStop` action declared on line 17 to those existing stories.

2025-01-14 17:07 UTC, binh-dam-ibigroup commented on packages/endpoints-overlay/src/endpoint.tsx
> +  viewNearby?: (arg: Location) => void;
Rename to `setViewNearby` to be consistent with the containing component.

2025-01-14 17:07 UTC, binh-dam-ibigroup commented on packages/endpoints-overlay/src/EndpointsOverlay.story.tsx
> +const setViewedStop = action("setViewedStop");
Rename to `setViewNearby`.

2025-01-14 17:59 UTC, amy-corson-ibigroup commented on packages/endpoints-overlay/src/EndpointsOverlay.story.tsx
> +export const EndpointsOverlayWithStopLink: ComponentStory<typeof EndpointsOverlay> = () => (
Whoops thank you for this catch!

2025-01-14 18:42 UTC, binh-dam-ibigroup commented on packages/endpoints-overlay/src/index.tsx
> +      viewNearby={setViewNearby}
Update this prop (2 instances)

2025-01-15 15:46 UTC, merged